"""empty message

Revision ID: b22545a5ac94
Revises: 
Create Date: 2023-12-10 21:14:56.284288

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b22545a5ac94'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Item',
    sa.Column('Product_id', sa.String(length=100), nullable=False),
    sa.Column('Product_name', sa.String(length=100), nullable=False),
    sa.Column('Product_url', sa.String(length=100), nullable=False),
    sa.Column('Image_url', sa.String(length=100), nullable=False),
    sa.Column('Brand', sa.String(length=100), nullable=False),
    sa.Column('Style', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('Product_id')
    )
    op.create_table('User_Profile',
    sa.Column('User_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('sex', sa.String(length=100), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('User_id')
    )
    op.create_table('Detailed_Item',
    sa.Column('Product_id', sa.String(length=100), nullable=False),
    sa.Column('Price', sa.Integer(), nullable=False),
    sa.Column('Review', sa.Integer(), nullable=False),
    sa.Column('Like', sa.Integer(), nullable=False),
    sa.Column('Category', sa.String(length=100), nullable=False),
    sa.Column('item_id', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['Product_id'], ['Item.Product_id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['Item.Product_id'], ),
    sa.PrimaryKeyConstraint('Product_id')
    )
    op.create_table('User_Item',
    sa.Column('index', sa.Integer(), nullable=False),
    sa.Column('User_id', sa.Integer(), nullable=True),
    sa.Column('Product_id', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['Product_id'], ['Item.Product_id'], ),
    sa.ForeignKeyConstraint(['User_id'], ['User_Profile.User_id'], ),
    sa.PrimaryKeyConstraint('index', 'Product_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('User_Item')
    op.drop_table('Detailed_Item')
    op.drop_table('User_Profile')
    op.drop_table('Item')
    # ### end Alembic commands ###
